spring: 
  profiles:
    active: dev
  datasource: 
    url: jdbc:mysql://192.168.55.85:3306/test
    username: yushiadmin
    password: 1FLASH1flash***
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    add-mappings: false
  redis:
    database: 0
    host: 11.24.17.51
    port: 6379
    password: test.redis
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level: {root: INFO, com.wotopten.crm.dao: DEBUG}

interceptor:
  path:
    action:


hello:
  msg: hello-ajajaj
